# Spring Boot application properties
server.port=8081
# Other properties can be added as needed
spring.data.mongodb.uri=mongodb+srv://joshualhc03:20051129@eyedra.etzck.mongodb.net/?retryWrites=true&w=majority&appName=eyedra
spring.data.mongodb.database=eyedra
spring.data.mongodb.authentication-database=admin

# Enable MongoDB repository
spring.data.mongodb.repositories.enabled=true

# Logging configuration
logging.level.org.springframework.data.mongodb=DEBUG
