spring:
  application:
    name: gateway-service-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-api
          uri: lb://user-service-api
          predicates:
            - Path=/api/v1/auth/**, /api/v1/user/**, /listener/**
          filters:
            - StripPrefix=0


        - id: community-service-api
          uri: lb://community-service-api
          predicates:
            - Path=/api/v1/community/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter


        - id: post-service-api
          uri: lb://post-service-api
          predicates:
            - Path=/api/v1/post/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter


        - id: reaction-service-api
          uri: lb://reaction-service-api
          predicates:
            - Path=/api/v1/reaction/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter


        - id: notification-service-api
          uri: lb://notification-service-api
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

