spring.application.name=notification-service-api

spring.data.mongodb.uri=mongodb+srv://eyedra:EyedraSe48@eyedra.etzck.mongodb.net/?retryWrites=true&w=majority&appName=eyedra
spring.data.mongodb.database=eyedra
spring.data.mongodb.authentication-database=admin
