spring.application.name=reaction-service-api
# Server configuration
server.port=8084
server.address=0.0.0.0
socket.port=5001
socket.threadPoolSize=10

# MongoDB configuration
spring.data.mongodb.uri=mongodb+srv://joshualhc03:20051129@eyedra.etzck.mongodb.net/?retryWrites=true&w=majority&appName=eyedra
spring.data.mongodb.database=eyedra
spring.data.mongodb.authentication-database=admin

# Enable MongoDB repository
spring.data.mongodb.repositories.enabled=true
spring.cloud.compatibility-verifier.enabled=false

# Logging configuration
logging.level.org.springframework.data.mongodb=DEBUG

# Disable Docker integration
spring.cloud.docker.enabled=false

# # Eureka server URL
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# # Enable actuator endpoints
user.service.url=http://localhost:8761/
