# Server configuration
server.port=8080
server.address=0.0.0.0

# MongoDB configuration
spring.data.mongodb.uri=mongodb+srv://joshualhc03:20051129@eyedra.etzck.mongodb.net/?retryWrites=true&w=majority&appName=eyedra
spring.data.mongodb.database=eyedra
spring.data.mongodb.authentication-database=admin

# Enable MongoDB repository
spring.data.mongodb.repositories.enabled=true

# Logging configuration
logging.level.org.springframework.data.mongodb=DEBUG


# Disable Docker Compose integration
spring.cloud.docker.enabled=false


cloudinary.cloud-name=drwycmmph
cloudinary.api-key=714797716448623
cloudinary.api-secret=XnbT-o69try9ir5TDkjb3EtjWac
