# Server configuration
server.port=8081
server.address=0.0.0.0
socket.port=5001
socket.threadPoolSize=10

# MongoDB configuration
spring.data.mongodb.uri=mongodb+srv://joshualhc03:20051129@eyedra.etzck.mongodb.net/?retryWrites=true&w=majority&appName=eyedra
spring.data.mongodb.database=eyedra
spring.data.mongodb.authentication-database=admin

# Enable MongoDB repository
spring.data.mongodb.repositories.enabled=true
spring.cloud.compatibility-verifier.enabled=false

# Logging configuration
logging.level.org.springframework.data.mongodb=DEBUG

# Disable Docker Compose integration
spring.cloud.docker.enabled=false

# cloudinary configuration
cloudinary.cloud-name=drwycmmph
cloudinary.api-key=714797716448623
cloudinary.api-secret=XnbT-o69try9ir5TDkjb3EtjWac

# Spring application name
spring.application.name=post-service-api

# # Eureka server URL
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# # Enable actuator endpoints
user.service.url=http://localhost:8761/

# Allow Bean Definition Overriding
spring.main.allow-bean-definition-overriding=true